### ISSUE TITLE
homebew tap of openscad

### ISSUE THREAD

**Issue by kbrock** [openscad/homebrew-tap#7]
The homebrew team is maintaining a link to openscad: [ref]

```
brew cask install openscad
```

It had a 2019 version which worked great.

[ref]: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/openscad.rb

**Comment by t-paul** [comment]
Yep, that's great. It's also mentioned on the [download](https://www.openscad.org/downloads.html) page.

So what's the issue for?

**Comment by kbrock** [comment]
sorry - brain flake.

I was trying to get this tap to work figured out how to use the other cask, and wanted to share this for others searching.

 looks like RTFM would have saved me a bunch of work here

thanks for supporting this fine project
and sorry for the unnecessary ping

**Comment by t-paul** [comment]
No worries, the ping was actually quite useful, I've cleaned up the old cruft and updated the readme to tell the current state.
